### ISSUE TITLE
Add way of getting current orientation

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/deviceorientation#11]
The API should provide some way to get request the current orientation without needing to subscribe to events.

**Comment by hexalys** [comment]
It's definitely lacking. Alternatively or in addition, any thoughts on normalizing the specs for all browsers to star firing Device Orientation at the same 'interactive' state of the document so it can be used at DOMContentLoaded?

Related post as I was trying to detect this capability: http://stackoverflow.com/a/30585637/1647538

**Comment by gmandyam** [comment]
Added label of VNext.  This can be considered as part of Generic Sensor API work.

**Comment by reillyeon** [comment]
I propose closing this issue as "won't fix". A Promise-returning API can easily be polyfilled like so,

```js
function getCurrentOrientation() {
  return new Promise((resolve) => {
    document.addEventListener('deviceorientation', (event) => {
      resolve(event);
    }, {once: true});
  });
}
```

The [Observable](https://github.com/WICG/observable) proposal would also extend all `EventTarget`s so that you could write:

```js
let event = (await document.on('deviceorientation').take(1).toArray())[0];
```
