### ISSUE TITLE
Internationalization Checklist

### ISSUE THREAD

**Issue by anssiko** [w3c/deviceorientation#132]
This issue is a record of the [Devices and Sensors Working Group](https://www.w3.org/das/)'s response to the [Internationalization Checklist](https://w3c.github.io/i18n-drafts/techniques/shortchecklist) for the [DeviceOrientation Event Specification](https://www.w3.org/TR/orientation-event/).

>- [ ] If the spec (or its implementation) contains any natural language text that will be read by a human (this includes error messages or other UI text, JSON strings, etc, etc),

Not directly, since the API specification does not contain or recommend any strings exposed to end users.

Some implementations may surface a permission prompt or an equivalent UI to the user when `requestPermission()` method is invoked. The contents of this UI is an implementation detail and any related text strings are expected to be localized to match the user's locale settings.

Some API attributes read by web developers only use self-documenting explicit English (`acceleration`, `accelerationIncludingGravity`, `rotationRate`).

>- [ ] If the spec (or its implementation) allows content authors to produce typographically appealing text, either in its own right, or in association with graphics.

N/A

>- [ ] If the spec (or its implementation) allows the user to point into text, creates text fragments, concatenates text, allows the user to select or step through text (using a cursor or other methods), etc.

N/A

>- [ ] If the spec (or its implementation) allows searching or matching of text, including syntax and identifiers

N/A

>- [ ] If the spec (or its implementation) sorts text

N/A

>- [ ] If the spec (or its implementation) captures user input

N/A

>- [ ] If the spec (or its implementation) deals with time in any way that will be read by humans and/or crosses time zone boundaries

Not directly. The specification defines acceleration and linear acceleration concepts whose values are expressed in meters per second squared (m/s2), an SI unit for acceleration.

>- [ ] If the spec (or its implementation) allows any character encoding other than UTF-8.

N/A

>- [ ] If the spec (or its implementation) defines markup.

N/A

>- [ ] If the spec (or its implementation) deals with names, addresses, time & date formats, etc

N/A

>- [ ] If the spec (or its implementation) describes a format or data that is likely to need localization.

N/A

>- [ ] If the spec (or its implementation) makes any reference to or relies on any cultural norms

N/A

## Summary

Based on this self-assessment the WG believes no Internationalization Considerations section is required.

**Comment by himorin** [comment]
I believe two marked items (1st natural language, 7th time) are not applicable to the DeviceOrientation.
For former, we don't define any error message (e.g. providing error code with description in natural language), also API attributes are just defined attribute name but not message from API or something.
For latter, target is [locale affected time or timezone](https://www.w3.org/TR/international-specs/#locale), but not general time related SI value.

**Comment by anssiko** [comment]
@himorin thanks for your review. I unchecked those two boxes but left the commentary in there to give reviewers related context. Hearing no other comments, I suggest the WG to initiate this review. I'm happy to take that action.
