### ISSUE TITLE
DeviceMotionEventInit interface members

### ISSUE THREAD

**Issue by jensl** [w3c/deviceorientation#14]
The DeviceMotionEventInit dictionary has members of interface type, DeviceAcceleration and DeviceRotationRate. Those interfaces have no interface objects, and no constructors, and thus can't be constructed by user scripts. Thus, populating the dictionary is difficult.

Should the dictionary perhaps reference sub-dictionaries (e.g. DeviceAccelerationInit / DeviceRotationRateInit) instead?

**Comment by foolip** [comment]
Same problem as in https://github.com/w3c/deviceorientation/issues/19

**Comment by timvolodine** [comment]
addressed in https://github.com/w3c/deviceorientation/pull/32

**Comment by foolip** [comment]
Changes in #32 LGTM
