### ISSUE TITLE
Set controls target? 

### ISSUE THREAD

**Issue by anagpuyol** [w3c/deviceorientation#15]
Hi, I was wondering if you guys had developed a method to set the target of these controls. I am working on a project where we want to walk users thru different views and we'd like to override the current orientation of the device with the target (direction) of the view so that they see specific objects in the scene.

Thanks! and amazing work!

**Comment by richtr** [comment]
This repository tracks the specification of providing the underlying hardware sensor data to web pages for web browsers to implement. Web developers should then use this 'raw data' that describes the device's orientation in physical space to transform objects within their web pages.

There are a number of useful libraries that may help here. For example, check out [three.js](http://threejs.org) that does allow you to set a target for device orientation controls (specifically, check out [this demo](http://threejs.org/examples/misc_controls_deviceorientation)).

It seems like you are looking for a library that provides these features so I will go ahead and close this issue as invalid for this repository.
