### ISSUE TITLE
Reach consensus on deprecation and removal of de facto standard init*Event() methods

### ISSUE THREAD

**Issue by reillyeon** [w3c/deviceorientation#35]
In issue #18 @foolip determined that the `DeviceMotionEvent.initDeviceMotionEvent()` and `DeviceOrientationEvent.initDeviceOrientationEvent()` methods which are implemented by Chrome, Edge, Firefox and Mobile Safari have extremely low usage and so should not be added to this specification. However, given the fact that these methods are supported by a large number of implementations consensus that removal is the right choice should be reached.

So far the only public signals on this topic come from [MSDN](https://msdn.microsoft.com/en-us/library/ff975459(v=vs.85).aspx) where it is documented that "as of Microsoft Edge, the `createEvent()`/`initEvent()` constructor pattern for synthetic events is deprecated." There is no specific mention of these methods.

**Comment by reillyeon** [comment]
Correction to the above, [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Event/initEvent) also lists `initEvent()` as deprecated.

**Comment by foolip** [comment]
Trying to figure out who might know about this from code etc. in the various engines:
* EdgeHTML: @adrianba has posted to the list, but I think he's OOO, so perhaps michaelchampion?
* Gecko: @khuey @smaug----?
* WebKit: @cdumez? (also Sam Weinig, but can't find on GitHub)

Between standardization and removal, do y'all have preferences?

**Comment by marcoscaceres** [comment]
@khuey left Mozilla a little while ago to do other fun things

**Comment by khuey** [comment]
Indeed.  Maybe try @bakulf?

**Comment by cdumez** [comment]
Since most engines have it, I'd personally prefer to standardize.

**Comment by smaug----** [comment]
init*Events() are deprecated at least in the sense that new event interface types shouldn't get them, but I don't see any strong reason to remove them if all the implementations support them.

Hmm, though, if we want to make the platform better and eventually remove all the init*Event methods
(and createEvent), then we should try to remove init*Events one by one.

Do we have up-to-date data about initDeviceMotionEvent and initDeviceOrientationEvent usage?

**Comment by foolip** [comment]
We have these use counters:
https://www.chromestatus.com/metrics/feature/timeline/popularity/865
https://www.chromestatus.com/metrics/feature/timeline/popularity/866

However, despite the fact that I closed https://github.com/w3c/deviceorientation/issues/18 I would be perfectly happy to see these standardized, and don't think we can possibly remove *all* of the `init*Event()` methods, because:
https://www.chromestatus.com/metrics/feature/timeline/popularity/867

I would, however, like to give them all exactly one required argument as in https://github.com/whatwg/dom/issues/387

For those that aren't interoperable yet, it's very possible that removing them from *n* engines could be a faster path to interop than adding them to *4-n*, depending on the numbers and usage.

**Comment by foolip** [comment]
Should also say that *if* there is one eager individual for each engine, I would support removal as well.

**Comment by travisleithead** [comment]
We would love to drop support for it. We are still plumbing Event constructors through for everything, so these won't have that support yet, but we'll get there. Meanwhile, it doesn't matter if no one is programmatically dispatching them in practice anyway.

So +1

**Comment by reillyeon** [comment]
@smaug----, given the usage numbers [above](https://github.com/w3c/deviceorientation/issues/35#issuecomment-284705273) what do you think?

**Comment by smaug----** [comment]
Dropping them sounds good.

**Comment by reillyeon** [comment]
Chrome will be removing these methods.

**Comment by reillyeon** [comment]
Closing this issue. Safari Mobile appears to be the only browser still implementing these methods.

**Comment by smaug----** [comment]
I see https://searchfox.org/mozilla-central/source/dom/webidl/DeviceOrientationEvent.webidl#16
