### ISSUE TITLE
devicemotion: rotationRate is not implemented according to specification

### ISSUE THREAD

**Issue by juncaidf** [w3c/deviceorientation#44]
In the devicemotion specification:
https://w3c.github.io/deviceorientation/spec-source-orientation.html#devicemotion
The rotationRate: "It must be expressed as the rate of change of the angles defined in section 4.1"
So it means the rotation axes should be the following:
z axis: alpha
x axis: beta
y axis: gamma

However, Chrome on Android, Firefox browser on Android, and Safari browser on iPhone, they all implement rotationRate as the following:
x axis: alpha
y axis: beta
z axis: gamma

Given that this feature has been implemented in this way for a while and all the above browsers implement it in the same way which is different from the specification, updating the specification seems a better and easy solution. What do you think? Thanks!

The chromium related issue:
https://bugs.chromium.org/p/chromium/issues/detail?id=541607

I also created a pull request:
https://github.com/w3c/deviceorientation/pull/43

Jun

**Comment by andybloch** [comment]
I don't think it's a good idea to break a specification to match a broken implementation. Fix the implementation. Alpha is the rotation around the z axis for deviceorientation, and rotationRate should match it. The only question is whether the spec should be left as-is, or whether it should be replaced by renaming alpha-beta-gamma (maybe to Alpha-Beta-Gamma?) and the old names deprecated and redefined to match the broken implementation to avoid breaking existing code. Either way, it would take about 5 minutes to make this fix.

**Comment by reillyeon** [comment]
The change to Chrome's behavior was discussed and approved [on this thread](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/ple1o7bFqEs) with the change becoming the default behavior in Chrome 66.

Someone with permission to do so please close this issue.

**Comment by anssiko** [comment]
(I think @timvolodine is still able to close this issue if we can grab his attention.)

**Comment by andybloch** [comment]
On that thread I only see discussion of fixing the units (radians/sec vs. degrees/sec), not fixing the axes.

**Comment by reillyeon** [comment]
Ah, my mistake. I still support updating the specification on the definition of the axis given that there is a defacto standard in place by the agreement on this behavior by a majority of mobile browsers.

**Comment by anssiko** [comment]
Slightly OT, but if someone is wondering why no spec progress recently:

The spec has been without a home after the Geolocation WG closed 30 April 2017, and as a side-effect has accummulated a bunch of open issues and PRs. We expect to resume work on this spec when the Devices and Sensors WG adopts it starting 1 July 2018. So bear with us for a little while!

Also, anyone interested in editing the spec, please get in touch :-)

**Comment by reillyeon** [comment]
Pull request #43 has been merged. Closing this issue.
