### ISSUE TITLE
[editorial] Convert the spec source to Bikeshed/ReSpec

### ISSUE THREAD

**Issue by anssiko** [w3c/deviceorientation#53]
As suggested by @xfq in #52 we should probably convert the spec source to Bikeshed/ReSpec to make it easier to publish.

As of now, this spec inherited from Geolocation WG has 29 errors (and 5 warnings) in the Pubrules checker: https://www.w3.org/pubrules/?url=https%3A%2F%2Fw3c.github.io%2Fdeviceorientation%2F&profile=WD-Echidna&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=true&patentPolicy=pp2004

**Comment by anssiko** [comment]
(Before conversion, it makes sense to try merge open PRs https://github.com/w3c/deviceorientation/pulls so they apply cleanly.)

**Comment by anssiko** [comment]
All open PRs have been merged. Any volunteers to attempt Bikeshed conversion?

When that’s done, we could do a WD release.

**Comment by mkruisselbrink** [comment]
I've converted a number of specs to Bikeshed in the past, so happy to do so here as well, if nobody else volunteers (not entirely sure when I'll have time to do so though, but it seems like this is a fairly short spec so I don't expect it to take much time).

**Comment by anssiko** [comment]
@mkruisselbrink, thanks, that'd be much appreciated. Any other volunteers to help in this effort, please let us know.

Slightly OT: the spec is also looking for a new editor (and after bikeshed conversion, being an editor of this spec is a much nicer experience). We don't expect there to be a lot of work remaining, since we're [chartered](https://www.w3.org/2018/06/devices-sensors-wg-charter.html) as follows for this spec: "The Devices and Sensors Working Group intends to fix remaining known issues and to finish its progress on the Recommendation track." That in particular implies no new features.

All - please let me know if you're interested in becoming an editor of this spec to help finish its progress on the Rec Track as our charter says.

**Comment by anssiko** [comment]
I took a stab at the conversion in #62, appreciate reviews.
