### ISSUE TITLE
Invalid IDL in DeviceMotionEventInit

### ISSUE THREAD

**Issue by bzbarsky** [w3c/deviceorientation#54]
The IDL says:

    dictionary DeviceMotionEventInit : EventInit {
      DeviceAccelerationInit? acceleration;
      DeviceAccelerationInit? accelerationIncludingGravity;
      DeviceRotationRateInit? rotationRate;
      double interval = 0;
    };

but  the IDL spec says:

> If the Type is an identifier followed by ?, then the identifier must identify an interface, enumeration, callback function or typedef.

and

> If the type of the dictionary member, after resolving typedefs, is a nullable type, its inner type must not be a dictionary type.

when discussing dictionary members in <https://heycam.github.io/webidl/#idl-dictionaries>.   So the  above IDL is not valid, and a conformant IDL parser will reject it.

**Comment by reillyeon** [comment]
We can update the spec but implementations will likely need to keep accepting null values for these members because both [Blink](https://chromium.googlesource.com/chromium/src/+/1e6e30b0e19a1d2d2db6e6b7184d26c741959d78/third_party/blink/renderer/modules/device_orientation/device_motion_event_init.idl) and [Gecko](https://hg.mozilla.org/mozilla-central/raw-file/ebeba937ca2a01df86d98089f2368bb975182dcc/dom/webidl/DeviceMotionEvent.webidl) mark these as optional.

**Comment by mkruisselbrink** [comment]
> We can update the spec but implementations will likely need to keep accepting null values for these members because both [Blink](https://chromium.googlesource.com/chromium/src/+/1e6e30b0e19a1d2d2db6e6b7184d26c741959d78/third_party/blink/renderer/modules/device_orientation/device_motion_event_init.idl) and [Gecko](https://hg.mozilla.org/mozilla-central/raw-file/ebeba937ca2a01df86d98089f2368bb975182dcc/dom/webidl/DeviceMotionEvent.webidl) mark these as optional.

Every member of a dictionary that is not marked as required is already optional. The `?` really doesn't do anything since both "null" and "undefined" get converted to a dictionary the same way anyway. So getting rid of the `?` shouldn't have any behavioral effect (although it's hard to discuss what the behavior is of what is written now, since what is written isn't valid WebIDL to begin with).

**Comment by reillyeon** [comment]
> Every member of a dictionary that is not marked as required is already optional. The `?` really doesn't do anything since both "null" and "undefined" get converted to a dictionary the same way anyway. So getting rid of the `?` shouldn't have any behavioral effect (although it's hard to discuss what the behavior is of what is written now, since what is written isn't valid WebIDL to begin with).

That's a good point.

**Comment by bzbarsky** [comment]
> since both "null" and "undefined" get converted to a dictionary the same way anyway.

That's actually not the case in the IDL spec right now.  Trying to align Gecko with that spec was the reason I was looking at this IDL at all in Gecko (where the invalid `?` is not present) and trying to understand what this spec's normative requirements are.

`null` becomes empty dictionary.  `undefined` in this case becomes "member not present" in the outer dictionary.

So passing `null` is valid, and will have the same behavior as passing `{}`.  Passing `undefined` currently has the same behavior in Gecko too, because Gecko doesn't quite follow the Web IDL spec for dictionary-typed members of dictionaries.   But if we fix that, we'll run into the problem of this spec not actually defining behavior when `undefined` is used...  I hadn't gotten to filing that issue yet.

**Comment by reillyeon** [comment]
> We can update the spec but implementations will likely need to keep accepting null values for these members because both [Blink](https://chromium.googlesource.com/chromium/src/+/1e6e30b0e19a1d2d2db6e6b7184d26c741959d78/third_party/blink/renderer/modules/device_orientation/device_motion_event_init.idl) and [Gecko](https://hg.mozilla.org/mozilla-central/raw-file/ebeba937ca2a01df86d98089f2368bb975182dcc/dom/webidl/DeviceMotionEvent.webidl) mark these as optional.

Correction to this comment. Gecko does not mark these members optional. I think I need better glasses.

Chromium's behavior when the optional flag is removed is to convert `null` to `{}` and all other invalid values to `null`. I created [a patch](https://chromium-review.googlesource.com/c/chromium/src/+/1239722) removing this flag and discovered that we have web tests [that fail](https://test-results.appspot.com/data/layout_results/linux_chromium_rel_ng/193150/layout-test-results/results.html) because of this change in behavior.

**Comment by bzbarsky** [comment]
> Gecko does not mark these members optional.

Dictionary members are optional by default unless marked `required`.  Are you perhaps confusing "optional" and "nullable"?

> Chromium's behavior when the optional flag is removed

Er... Chromium allows the invalid IDL?  Is there a bug reported on that for Chromium?

> is to convert null to {} and all other invalid values to null

Converting explicit `null` to empty dictionary is correct per spec.   Converting other invalid values to anything (other than throwing an exception).... is totally not what the spec says.  Is there a bug reported on that for Chromium?

**Comment by reillyeon** [comment]
> > Gecko does not mark these members optional.
> 
> Dictionary members are optional by default unless marked `required`. Are you perhaps confusing "optional" and "nullable"?

Yes, I mean "nullable."

> > Chromium's behavior when the optional flag is removed
> 
> Er... Chromium allows the invalid IDL? Is there a bug reported on that for Chromium?

Yes, Chromium allows the invalid IDL. For reference for the current behavior I recommend looking at [device_orientation/motion/optional-event-properties.html](https://chromium.googlesource.com/chromium/src/+/e2e7cd911060f081cec552e230701a2366b12d0d/third_party/WebKit/LayoutTests/device_orientation/motion/optional-event-properties.html).

There are no bugs that I can find currently filed for this mismatch with the WebIDL specification but I might be missing context here because I am not on the team responsible for the WebIDL bindings generator.

**Comment by bzbarsky** [comment]
> For reference for the current behavior I recommend looking at device_orientation/motion/optional-event-properties.html.

OK, that test is definitely testing for behavior that is not allowed by the IDL spec.  The test that passes `acceleration: null` should have the same behavior as passing `acceleration: []`, for example.  It looks like the test was written based on an implementation, not based on the spec... :(

**Comment by bzbarsky** [comment]
Updating the test sounds great.

As far as the comments in #55 about what is specified or not...

There's no actual text anywhere in https://w3c.github.io/deviceorientation/#devicemotion that describes the steps for the `DeviceMotionEvent` constructor, or indeed any of the other constructors in this specification.  In particular, they do not define any https://dom.spec.whatwg.org/#concept-event-constructor-ext

In the absence of "event constructing steps", https://dom.spec.whatwg.org/#inner-event-creation-steps will end up doing:

> For each _member_ → _value_ in _dictionary,_ if _event_ has an attribute whose identifier is _member_, then initialize that attribute to _value_

OK, so let's take a look at the `acceleration` attribute of `DeviceMotionEventInit`.  This is of type `DeviceAccelerationInit` but the corresponding attribute on the event is of type `DeviceAcceleration?`.  It's not obvious how exactly to initialize the latter from the former.  @annevk how should this work exactly?  Even fixing it up via the "event construction steps" doesn't technically help, because those run after that "initialize that attribute" step...  Maybe the "initialize that attribute" step should not run if the types don't match?

Anyway, the simplest thing here from my point of view would be to:

1. Clarify that https://dom.spec.whatwg.org/#inner-event-creation-steps step 4 does nothing for attributes whose type does not match the init dictionary.
2. Define "event  construction steps" that if the value is not present in the dictionary initialize the attribute to null, else initialize the attribute to a `DeviceAcceleration` whose properties are set to the same values as the values in the `DeviceAccelerationInit`.

**Comment by bzbarsky** [comment]
> if the value is not present in the dictionary initialize the attribute to null

Or just do nothing, since that value starts off as null at object creation anyway.

**Comment by annevk** [comment]
@bzbarsky these kind of events were not really envisioned when that was written down (and I can't find an upstream issue about accounting for them either). It's not immediately clear to me what would be best here. If this is becoming a pattern we might need something better than simply ignoring type mismatches and hoping it's fixed up in post.

**Comment by bzbarsky** [comment]
@annevk I think people are sticking all sorts of stuff in event init dictionaries...

**Comment by bzbarsky** [comment]
I filed https://bugs.chromium.org/p/chromium/issues/detail?id=890375 on the one obvious bug in Chromium's IDL compiler here.  It's not clear to me from the above discussion whether there are additional bugs there or not, because there are contradictory statements  about what the Chromium behavior is in various cases.

@reillyeon can you please clarify what the behavior ends up being in Chromium once the invalid `?` are removed?

**Comment by reillyeon** [comment]
In Chromium, when the invalid '?' are removed then you get the following,

```javascript
> new DeviceMotionEvent('', {acceleration: {}}).acceleration
DeviceAcceleration {x: null, y: null, z: null}
> new DeviceMotionEvent('', {acceleration: null}).acceleration
DeviceAcceleration {x: null, y: null, z: null}
> new DeviceMotionEvent('', {acceleration: undefined}).acceleration
null
> new DeviceMotionEvent('', {}).acceleration
null
```

Based on my understanding from the discussion above this is correct according to the WebIDL specification.

The change from the non-compliant behavior is in this case,

```javascript
> new DeviceMotionEvent('', {acceleration: null}).acceleration
null
```

**Comment by bzbarsky** [comment]
Thank you.  That behavior all looks correct, yes, modulo the deviceorientation spec not actually specifying it yet.   But the binding parts look fine.
