### ISSUE TITLE
Remove [NoInterfaceObject]

### ISSUE THREAD

**Issue by annevk** [w3c/deviceorientation#58]
Carefully consider with what name to expose these interfaces and then please drop this. We're going to remove it from IDL per https://github.com/heycam/webidl/issues/430 and https://github.com/heycam/webidl/pull/609.

**Comment by anssiko** [comment]
@annevk, thanks for the heads up.

All - `DeviceAcceleration` and `DeviceRotationRate` are the current names that are not exposed. Any concerns in exposing these interfaces using these names?

Opening the issue for discussion and suggestions.

**Comment by kenchris** [comment]
These are also the "deprecated APIs" as they are being replaced with Generic Sensors, so exposing more now seems unfortunately

**Comment by kenchris** [comment]
@reillyeon @slighlylate

**Comment by reillyeon** [comment]
For reference the interfaces are,

```
interface DeviceAcceleration {
  readonly attribute double? x;
  readonly attribute double? y;
  readonly attribute double? z;
};

interface DeviceRotationRate {
  readonly attribute double? alpha;
  readonly attribute double? beta;
  readonly attribute double? gamma;
};
```

These are both pretty generic vectors. I wish we could reuse [`DOMPointReadOnly`](https://www.w3.org/TR/geometry-1/#dompointreadonly). Maybe before removing [NoInterfaceObject] we could rename them to something like `DeviceMotionEventAcceleration` and `DeviceMotionEventRotationRate` or `DeviceAccelerationLegacy` and `DeviceRotationRateLegacy` just to highlight that these types are part of this API.

**Comment by anssiko** [comment]
Thanks @reillyeon, `DeviceMotionEventAcceleration` and `DeviceMotionEventRotationRate` seem like good proposals to me.

**Comment by annevk** [comment]
@reillyeon yes, though I believe we only expose these APIs on Android and might put them behind a permission or disable them per #57. That's still under discussion.

**Comment by anssiko** [comment]
@cdumez, we have Google @reillyeon and Mozilla @annevk  OK'ing this rather minor PR https://github.com/w3c/deviceorientation/pull/63 that fixes this issue. We'll merge the PR unless we hear concerns from you.
