### ISSUE TITLE
webkitCompassHeading / webkitCompassAccuracy

### ISSUE THREAD

**Issue by richtr** [w3c/deviceorientation#6]
We need to decide if we want to incorporate Apple's webkitCompassHeading and webkitCompassAccuracy in to the specification. iOS-based implementations of Device Orientation Events provide an arbitary, non-absolute 'alpha' reading which does not lend itself well to Augmented Reality use cases.

The background reason for this decision can be read @ http://lists.w3.org/Archives/Public/public-geolocation/2011Jul/0014.html

More information on both properties is currently documented @ https://developer.apple.com/library/safari/documentation/SafariDOMAdditions/Reference/DeviceOrientationEventClassRef/DeviceOrientationEvent/DeviceOrientationEvent.html#//apple_ref/javascript/instp/DeviceOrientationEvent/webkitCompassHeading

**Comment by RByers** [comment]
Perhaps if we have both absolute and relative events (#21), then `webkitCompassHeading` is no longer useful?

**Comment by timvolodine** [comment]
since we have updated the spec to include 'deviceorientationabsolute' events to address potential AR use cases this issue is no longer relevant.
