### ISSUE TITLE
What is difference with Gyroscope API ?

### ISSUE THREAD

**Issue by GrosSacASac** [w3c/deviceorientation#61]
About [w3c/gyroscope](https://github.com/w3c/gyroscope) , what is difference ? Other than the fact that deviceorientation is purely event-driven and gyrospcope requires instantiation.

**Comment by anssiko** [comment]
In short, deviceorientation is a fusion sensor, while gyroscope is a low-level sensor.

Please refer to the web developer-focused article https://developers.google.com/web/updates/2017/09/sensors-for-the-web and the explainer https://w3c.github.io/motion-sensors/ for more details. Hope this helps!
