### ISSUE TITLE
Set up automatic Bikeshed compilation

### ISSUE THREAD

**Issue by reillyeon** [w3c/deviceorientation#67]
The title says it all.

**Comment by anssiko** [comment]
I suspect this is the right howto: https://github.com/rtoy/auto-deploy-spec

Just noting @fxq set up the Bikeshed auto-deployment for geolocation-sensor in https://github.com/w3c/geolocation-sensor/commit/0703c5bc2b1c1f66edd6a8ef4172a94b8067e205

**Comment by marcoscaceres** [comment]
Fixed by https://github.com/w3c/deviceorientation/blob/main/.github/workflows/auto-publish.yml
