### ISSUE TITLE
DeviceMotion only works once at init and return null value 

### ISSUE THREAD

**Issue by NjnuTZhou** [w3c/deviceorientation#77]
Hi!
i have met a question when using DeviceMotion event, it only returns a value of  null when init the app.

**Comment by reillyeon** [comment]
This is the specified behavior when the platform does not have device motion sensors. If you think it should be working on your device please file an issue against the browser you are testing with. This repository is just the specification.

**Comment by NjnuTZhou** [comment]
Thank you for your reply!
This behaviour appeared when I tested it in my phone(vivo X9S plus).However, When i used DeviceOrientation it returns specific value. Besides, my phone returns specific result using cordova-plugin-device-motion plugin.
I have checked hardware in my phone, and it does have gyroscope and Accelerometer. Soit may not be the platform's probelm?
Thank you!




------------------ 原始邮件 ------------------
发件人: "Reilly Grant"<notifications@github.com>;
发送时间: 2019年7月19日(星期五) 凌晨0:27
收件人: "w3c/deviceorientation"<deviceorientation@noreply.github.com>;
抄送: "咖啡糖，甜蜜"<1084146755@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [w3c/deviceorientation] DeviceMotion only works once at init andreturn null value  (#77)




This is the specified behavior when the platform does not have device motion sensors. If you think it should be working on your device please file an issue against the browser you are testing with. This repository is just the specification.
