### ISSUE TITLE
[Callback] extended attributes

### ISSUE THREAD

**Issue by anssiko** [w3c/deviceorientation#9]
WebIDL dropped [Callback] extended attributes in its 07 February 2012 – LCWD #3, see:

http://www.w3.org/TR/WebIDL/#changes

DeviceAcceleration and DeviceRotationRate should align.

**Comment by foolip** [comment]
@richtr, this was the weird extended attribute I was talking about today. Seems like it should simply be removed.

**Comment by foolip** [comment]
@timvolodine, are you taking pull requests on this spec?

**Comment by timvolodine** [comment]
@foolip sure, go ahead if you have any proposals
